### ISSUE TITLE
Conditional steps

### ISSUE THREAD

**Issue by rabol** [laravel-arcanist/arcanist#10]
Hi

Is there a way to have conditional steps

e.g. for a registration process, if one input on the first step say company, then the second step should be different that if the input say private

**Comment by ksassnowski** [comment]
Hi,

conditional steps currently aren't supported. This would make the redirection logic as well as determining if a user can access a specific step or not much more complicated.

What you can do instead is render different fields in you step's template depending on a value from a previous step. This might not work if the conditional step would be wildly different, however.
