### ISSUE TITLE
Action payload doesn't include data from the last step

### ISSUE THREAD

**Issue by jamessessford** [laravel-arcanist/arcanist#2]
Hi there,

Firstly, I'm having an amazing time playing with this package, thank you for the time & effort you've put in to it!

I noticed that I was getting a 500 error when trying to access data in the payload of my Action class but only on the first time I tried to submit, if I refreshed it worked fine.

I traced this through in the code (`AbstractWizard.php`) and found that the instance doesn't have access to the updated data yet in `processLastStep` - I'm assuming it's been persisted but not reloaded/attached to the instance straight away.

I fixed this on the example I'm working with by reloading the wizard after the `saveStepData` call in the update function.

*EDIT*: I'm also using the inertia-response-renderer package incase that infromation is helpful 

***Disclaimer***

It's highly likely I'm using this wrong so if I am, I apologise for wasting your time,

Cheers!

**Comment by ksassnowski** [comment]
Hey, thanks for trying out the package!

I’ve noticed this problem before as well, so that’s definitely a bug. I think I know how I want to solve this, so I reckon it should be fixed in the 0.2.0 release.

**Comment by jamessessford** [comment]
Cheers bud, feel free to close!

**Comment by ksassnowski** [comment]
I’ll leave this open until it’s fixed since this is a legitimate bug 😅

**Comment by ksassnowski** [comment]
Fixed in version 0.2.0 (https://github.com/laravel-arcanist/arcanist/releases/tag/0.2.0)
