### ISSUE TITLE
Access level to fields() must be public

### ISSUE THREAD

**Issue by bwdb-jmichael** [laravel-arcanist/arcanist#38]
Hello,

First of all I'd like to say I'm loving Arcanist and the documentation is cheeky and spectacular.

I am currently using Laravel Homestead which has PHP 8 and Laravel 8. The error I get is 

`
2022/01/19 17:03:17 [error] 17605#17605: *746 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access level to App\Wizards\Application\Steps\Step01_BasicInformation::fields() must be public (as in class Arcanist\WizardStep) in /home/vagrant/code/.../app/Wizards/Application/Steps/Step01_BasicInformation.php on line 20PHP message: PHP Fatal error:  Access level to App\Wizards\Application\Steps\Step01_BasicInformation::fields() must be public (as in class Arcanist\WizardStep) in /home/vagrant/code/.../app/Wizards/Application/Steps/Step01_BasicInformation.php on line 20" while reading response header from upstream, client: 10.22.33.1, server: app.test, request: "GET /wizard/apply HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "app.test"`

I ran into an issue when deploying it today following the documentation here: https://laravel-arcanist.com/getting-started. It shows under the step slug example that the fields functions should be protected as seen below:

`protected function fields(): array
    {
        return [
            // Field::make('field-name')
            //   ->rules(['required']),
        ];
    }`

However when doing this I get the error seen above. I followed this over to src/WizardStep.php and modified it from

`    public function fields(): array
    {
        return [];
    }
` 

to

`    protected function fields(): array
    {
        return [];
    }
`

I'm still in the middle of deploying this so I'm not sure what the effects of this are, but it seems to have cleared up the error for now. I'm not quite sure what the correct state should be for the fields function, but I thought I'd pass this along to see if this is user error or a mixup between when the documentation was written and a github revision.

Appreciate the insight and your time.

**Comment by ksassnowski** [comment]
This was a mistake in the documentation. The `fields` method should be public. I've updated the docs accordingly. Thanks for pointing this out :)
