### ISSUE TITLE
arc lint doesnt see all the paths in the directory

### ISSUE THREAD

**Issue by vimalzxc** [laravel-arcanist/arcanist#54]
When I do an arc lint, I only get 7/100+ files in the directory

Tried different regex for include but cant seem to get it to see everything

arclint file
`
{
  "linters": {
    "cppcheck": {
      "type": "cppcheck",
      "exclude" : [
      ],
      "include": [
          "(.*\\.c$)",
        "(.*\\.h$)"
      ]
    }
  }
}
`

**Comment by ksassnowski** [comment]
Are.. you sure you posted this on the correct repository?

**Comment by vimalzxc** [comment]
Sorry
