### ISSUE TITLE
Add artisan command for step/wizard creation

### ISSUE THREAD

**Issue by Wulfheart** [laravel-arcanist/arcanist#7]
Something to automatically create a new wizard folder in the `App\Wizards` namespace and steps in `App\Wizards\<name>\Steps` would be nice.

Proposed commands:
`php artisan make:arcanist Registration`
Would create a Wizard at `App\Wizards\Registration`.

`php artisan make:arcanist Registration --steps=UsernameAndPasswordStep,AnnoyingNewsletterStep`
Would create a Wizard at `App\Wizards\Registration` if not exists and add two steps.

If you are willing to accept it, I'd contribute it.

**Comment by ksassnowski** [comment]
Hey, thanks for wanting to contribute!

This is something that I’ve already started working on, so it’s good that you opened an issue first 😅 I hadn’t considered adding a `--step` flag to the wizard command, however, so that’s something I’ll definitely incorporate!

**Comment by Wulfheart** [comment]
I'm looking forward to watch the stream as a good night story. 😉
